// <auto-generated />
using System;
using CryptoTracker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoTracker.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418170342_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CryptoTracker.API.Models.CryptoCoin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CoinGeckoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsTracked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CoinGeckoId")
                        .IsUnique();

                    b.ToTable("CryptoCoins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "bitcoin",
                            IsTracked = true,
                            Name = "Bitcoin",
                            Symbol = "BTC"
                        },
                        new
                        {
                            Id = 2,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "ethereum",
                            IsTracked = true,
                            Name = "Ethereum",
                            Symbol = "ETH"
                        },
                        new
                        {
                            Id = 3,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "tether",
                            IsTracked = true,
                            Name = "Tether",
                            Symbol = "USDT"
                        },
                        new
                        {
                            Id = 4,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "binancecoin",
                            IsTracked = true,
                            Name = "BNB",
                            Symbol = "BNB"
                        },
                        new
                        {
                            Id = 5,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "solana",
                            IsTracked = true,
                            Name = "Solana",
                            Symbol = "SOL"
                        },
                        new
                        {
                            Id = 6,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "usd-coin",
                            IsTracked = true,
                            Name = "USD Coin",
                            Symbol = "USDC"
                        },
                        new
                        {
                            Id = 7,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "ripple",
                            IsTracked = true,
                            Name = "XRP",
                            Symbol = "XRP"
                        },
                        new
                        {
                            Id = 8,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "staked-ether",
                            IsTracked = true,
                            Name = "Lido Staked Ether",
                            Symbol = "STETH"
                        },
                        new
                        {
                            Id = 9,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "dogecoin",
                            IsTracked = true,
                            Name = "Dogecoin",
                            Symbol = "DOGE"
                        },
                        new
                        {
                            Id = 10,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "cardano",
                            IsTracked = true,
                            Name = "Cardano",
                            Symbol = "ADA"
                        },
                        new
                        {
                            Id = 11,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "avalanche-2",
                            IsTracked = true,
                            Name = "Avalanche",
                            Symbol = "AVAX"
                        },
                        new
                        {
                            Id = 12,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "tron",
                            IsTracked = true,
                            Name = "TRON",
                            Symbol = "TRX"
                        },
                        new
                        {
                            Id = 13,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "chainlink",
                            IsTracked = true,
                            Name = "Chainlink",
                            Symbol = "LINK"
                        },
                        new
                        {
                            Id = 14,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "polkadot",
                            IsTracked = true,
                            Name = "Polkadot",
                            Symbol = "DOT"
                        },
                        new
                        {
                            Id = 15,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "matic-network",
                            IsTracked = true,
                            Name = "Polygon",
                            Symbol = "MATIC"
                        },
                        new
                        {
                            Id = 16,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "shiba-inu",
                            IsTracked = true,
                            Name = "Shiba Inu",
                            Symbol = "SHIB"
                        },
                        new
                        {
                            Id = 17,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "litecoin",
                            IsTracked = true,
                            Name = "Litecoin",
                            Symbol = "LTC"
                        },
                        new
                        {
                            Id = 18,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "dai",
                            IsTracked = true,
                            Name = "Dai",
                            Symbol = "DAI"
                        },
                        new
                        {
                            Id = 19,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "uniswap",
                            IsTracked = true,
                            Name = "Uniswap",
                            Symbol = "UNI"
                        },
                        new
                        {
                            Id = 20,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "bitcoin-cash",
                            IsTracked = true,
                            Name = "Bitcoin Cash",
                            Symbol = "BCH"
                        },
                        new
                        {
                            Id = 21,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "stellar",
                            IsTracked = true,
                            Name = "Stellar",
                            Symbol = "XLM"
                        },
                        new
                        {
                            Id = 22,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "internet-computer",
                            IsTracked = true,
                            Name = "Internet Computer",
                            Symbol = "ICP"
                        },
                        new
                        {
                            Id = 23,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "cosmos",
                            IsTracked = true,
                            Name = "Cosmos",
                            Symbol = "ATOM"
                        },
                        new
                        {
                            Id = 24,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "ethereum-classic",
                            IsTracked = true,
                            Name = "Ethereum Classic",
                            Symbol = "ETC"
                        },
                        new
                        {
                            Id = 25,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "monero",
                            IsTracked = true,
                            Name = "Monero",
                            Symbol = "XMR"
                        },
                        new
                        {
                            Id = 26,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "okb",
                            IsTracked = true,
                            Name = "OKB",
                            Symbol = "OKB"
                        },
                        new
                        {
                            Id = 27,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "filecoin",
                            IsTracked = true,
                            Name = "Filecoin",
                            Symbol = "FIL"
                        },
                        new
                        {
                            Id = 28,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "hedera-hashgraph",
                            IsTracked = true,
                            Name = "Hedera",
                            Symbol = "HBAR"
                        },
                        new
                        {
                            Id = 29,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "lido-dao",
                            IsTracked = true,
                            Name = "Lido DAO",
                            Symbol = "LDO"
                        },
                        new
                        {
                            Id = 30,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "arbitrum",
                            IsTracked = true,
                            Name = "Arbitrum",
                            Symbol = "ARB"
                        },
                        new
                        {
                            Id = 31,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "vechain",
                            IsTracked = true,
                            Name = "VeChain",
                            Symbol = "VET"
                        },
                        new
                        {
                            Id = 32,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "the-open-network",
                            IsTracked = true,
                            Name = "Toncoin",
                            Symbol = "TON"
                        },
                        new
                        {
                            Id = 33,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "near",
                            IsTracked = true,
                            Name = "NEAR Protocol",
                            Symbol = "NEAR"
                        },
                        new
                        {
                            Id = 34,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "algorand",
                            IsTracked = true,
                            Name = "Algorand",
                            Symbol = "ALGO"
                        },
                        new
                        {
                            Id = 35,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "the-graph",
                            IsTracked = true,
                            Name = "The Graph",
                            Symbol = "GRT"
                        },
                        new
                        {
                            Id = 36,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "fantom",
                            IsTracked = true,
                            Name = "Fantom",
                            Symbol = "FTM"
                        },
                        new
                        {
                            Id = 37,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "aave",
                            IsTracked = true,
                            Name = "Aave",
                            Symbol = "AAVE"
                        },
                        new
                        {
                            Id = 38,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "elrond-erd-2",
                            IsTracked = true,
                            Name = "MultiversX",
                            Symbol = "EGLD"
                        },
                        new
                        {
                            Id = 39,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "eos",
                            IsTracked = true,
                            Name = "EOS",
                            Symbol = "EOS"
                        },
                        new
                        {
                            Id = 40,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "theta-token",
                            IsTracked = true,
                            Name = "Theta Network",
                            Symbol = "THETA"
                        },
                        new
                        {
                            Id = 41,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "optimism",
                            IsTracked = true,
                            Name = "Optimism",
                            Symbol = "OP"
                        },
                        new
                        {
                            Id = 42,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "maker",
                            IsTracked = true,
                            Name = "Maker",
                            Symbol = "MKR"
                        },
                        new
                        {
                            Id = 43,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "the-sandbox",
                            IsTracked = true,
                            Name = "The Sandbox",
                            Symbol = "SAND"
                        },
                        new
                        {
                            Id = 44,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "axie-infinity",
                            IsTracked = true,
                            Name = "Axie Infinity",
                            Symbol = "AXS"
                        },
                        new
                        {
                            Id = 45,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "decentraland",
                            IsTracked = true,
                            Name = "Decentraland",
                            Symbol = "MANA"
                        },
                        new
                        {
                            Id = 46,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "flow",
                            IsTracked = true,
                            Name = "Flow",
                            Symbol = "FLOW"
                        },
                        new
                        {
                            Id = 47,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "chiliz",
                            IsTracked = true,
                            Name = "Chiliz",
                            Symbol = "CHZ"
                        },
                        new
                        {
                            Id = 48,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "curve-dao-token",
                            IsTracked = true,
                            Name = "Curve DAO Token",
                            Symbol = "CRV"
                        },
                        new
                        {
                            Id = 49,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "synthetix-network-token",
                            IsTracked = true,
                            Name = "Synthetix",
                            Symbol = "SNX"
                        },
                        new
                        {
                            Id = 50,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoinGeckoId = "pancakeswap-token",
                            IsTracked = true,
                            Name = "PancakeSwap",
                            Symbol = "CAKE"
                        });
                });

            modelBuilder.Entity("CryptoTracker.API.Models.CryptoPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CryptoCoinId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(20,8)");

                    b.Property<decimal?>("PriceChange24h")
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Volume24h")
                        .HasColumnType("decimal(30,2)");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("CryptoCoinId", "RecordedAt");

                    b.ToTable("CryptoPrices");
                });

            modelBuilder.Entity("CryptoTracker.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CryptoTracker.API.Models.CryptoPrice", b =>
                {
                    b.HasOne("CryptoTracker.API.Models.CryptoCoin", "CryptoCoin")
                        .WithMany("Prices")
                        .HasForeignKey("CryptoCoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CryptoCoin");
                });

            modelBuilder.Entity("CryptoTracker.API.Models.CryptoCoin", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
