// <auto-generated />
using System;
using CryptoTracker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoTracker.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317152612_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CryptoTracker.API.Models.CryptoCoin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CoinGeckoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsTracked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CoinGeckoId")
                        .IsUnique();

                    b.ToTable("CryptoCoins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedAt = new DateTime(2026, 3, 17, 15, 26, 11, 794, DateTimeKind.Utc).AddTicks(4104),
                            CoinGeckoId = "bitcoin",
                            IsTracked = true,
                            Name = "Bitcoin",
                            Symbol = "BTC"
                        },
                        new
                        {
                            Id = 2,
                            AddedAt = new DateTime(2026, 3, 17, 15, 26, 11, 794, DateTimeKind.Utc).AddTicks(4106),
                            CoinGeckoId = "ethereum",
                            IsTracked = true,
                            Name = "Ethereum",
                            Symbol = "ETH"
                        },
                        new
                        {
                            Id = 3,
                            AddedAt = new DateTime(2026, 3, 17, 15, 26, 11, 794, DateTimeKind.Utc).AddTicks(4108),
                            CoinGeckoId = "solana",
                            IsTracked = true,
                            Name = "Solana",
                            Symbol = "SOL"
                        },
                        new
                        {
                            Id = 4,
                            AddedAt = new DateTime(2026, 3, 17, 15, 26, 11, 794, DateTimeKind.Utc).AddTicks(4109),
                            CoinGeckoId = "binancecoin",
                            IsTracked = true,
                            Name = "BNB",
                            Symbol = "BNB"
                        },
                        new
                        {
                            Id = 5,
                            AddedAt = new DateTime(2026, 3, 17, 15, 26, 11, 794, DateTimeKind.Utc).AddTicks(4111),
                            CoinGeckoId = "cardano",
                            IsTracked = true,
                            Name = "Cardano",
                            Symbol = "ADA"
                        });
                });

            modelBuilder.Entity("CryptoTracker.API.Models.CryptoPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CryptoCoinId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(20,8)");

                    b.Property<decimal?>("PriceChange24h")
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Volume24h")
                        .HasColumnType("decimal(30,2)");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("CryptoCoinId", "RecordedAt");

                    b.ToTable("CryptoPrices");
                });

            modelBuilder.Entity("CryptoTracker.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CryptoTracker.API.Models.CryptoPrice", b =>
                {
                    b.HasOne("CryptoTracker.API.Models.CryptoCoin", "CryptoCoin")
                        .WithMany("Prices")
                        .HasForeignKey("CryptoCoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CryptoCoin");
                });

            modelBuilder.Entity("CryptoTracker.API.Models.CryptoCoin", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
